# Feature Engineering

In [22]:
import numpy as np
import pandas as pd

In [23]:
data = pd.read_csv("Phishing_URL_ds_5percent_missing.csv").drop(columns=["FILENAME"])
with pd.option_context("display.max_columns", None):
    display(data.head())

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS,LineOfCode,LargestLineLength,HasTitle,Title,DomainTitleMatchScore,URLTitleMatchScore,HasFavicon,Robots,IsResponsive,NoOfURLRedirect,NoOfSelfRedirect,HasDescription,NoOfPopup,NoOfiFrame,HasExternalFormSubmit,HasSocialNet,HasSubmitButton,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31.0,NaN,24.0,0.0,com,100.0,1.000000,0.522907,0.061933,3.0,1.0,0.0,0.0,0.0,18.0,0.581,0.0,0.0,0.0,0.0,0.0,1.0,0.032,NaN,558.0,9381.0,1.0,à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µ...,0.000000,0.000000,0.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,34.0,20.0,NaN,119.0,0.0,124.0,1.0
1,https://www.uni-mainz.de,23.0,www.uni-mainz.de,16.0,0.0,NaN,100.0,0.666667,0.032650,0.050207,2.0,1.0,0.0,0.0,0.0,9.0,0.391,0.0,0.0,0.0,0.0,0.0,2.0,0.087,1.0,618.0,9381.0,1.0,johannes gutenberg-universitÃ¤t mainz,55.555556,55.555556,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,50.0,9.0,8.0,39.0,0.0,217.0,1.0
2,https://www.voicefmradio.co.uk,NaN,www.voicefmradio.co.uk,22.0,0.0,uk,100.0,0.866667,0.028555,0.064129,2.0,2.0,0.0,NaN,0.0,15.0,0.517,0.0,0.0,0.0,0.0,0.0,2.0,0.069,1.0,467.0,682.0,1.0,voice fm southampton,46.666667,46.666667,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,10.0,2.0,7.0,42.0,2.0,5.0,1.0
3,https://www.sfnmjournal.com,26.0,www.sfnmjournal.com,19.0,0.0,com,100.0,1.000000,0.522907,NaN,3.0,1.0,NaN,0.0,0.0,13.0,0.500,0.0,0.0,0.0,0.0,NaN,1.0,0.038,NaN,6356.0,26824.0,1.0,home page: seminars in fetal and neonatal medi...,0.000000,0.000000,0.0,1.0,1.0,0.0,0.0,0.0,1.0,12.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,NaN,3.0,27.0,15.0,22.0,1.0,31.0,1.0
4,https://www.rewildingargentina.org,33.0,www.rewildingargentina.org,26.0,0.0,org,100.0,1.000000,0.079963,0.059441,3.0,1.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.030,1.0,6089.0,28404.0,1.0,fundaciÃ³n rewilding argentina,100.000000,100.000000,0.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0,0.0,1.0,1.0,NaN,0.0,1.0,1.0,0.0,1.0,244.0,15.0,34.0,72.0,1.0,85.0,1.0

In [24]:
data.select_dtypes(include="object").head()

,URL,Domain,TLD,Title
0,https://www.southbankmosaics.com,NaN,com,à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µ...
1,https://www.uni-mainz.de,www.uni-mainz.de,NaN,johannes gutenberg-universitÃ¤t mainz
2,https://www.voicefmradio.co.uk,www.voicefmradio.co.uk,uk,voice fm southampton
3,https://www.sfnmjournal.com,www.sfnmjournal.com,com,home page: seminars in fetal and neonatal medi...
4,https://www.rewildingargentina.org,www.rewildingargentina.org,org,fundaciÃ³n rewilding argentina

In [25]:
with pd.option_context("display.max_columns", None):
    display(data[data["NoOfEqualsInURL"] > 0].head())

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS,LineOfCode,LargestLineLength,HasTitle,Title,DomainTitleMatchScore,URLTitleMatchScore,HasFavicon,Robots,IsResponsive,NoOfURLRedirect,NoOfSelfRedirect,HasDescription,NoOfPopup,NoOfiFrame,HasExternalFormSubmit,HasSocialNet,HasSubmitButton,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
31,NaN,91.0,ipfs.io,7.0,0.0,io,9.669201,1.000000,0.012927,0.041483,2.0,0.0,0.0,0.0,0.0,69.0,0.758,7.0,0.077,1.0,1.0,0.0,5.0,0.077,1.0,105.0,1607.0,1.0,roundcube webmail :: welcome to roundcube webmail,0.0,2.531646,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,6.0,0.0,0.0,2.0,0.0
45,https://pontosapontamentolu.com/gclid/=/c/?gcl...,140.0,pontosapontamentolu.com,23.0,0.0,com,9.203795,1.000000,0.522907,0.037272,3.0,0.0,0.0,0.0,0.0,99.0,0.707,19.0,0.136,2.0,1.0,0.0,11.0,NaN,1.0,11.0,148.0,1.0,pontosapontamentolugclid=c?gclid=ishecabh95cvb...,0.0,100.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91,http://tkmowpikuk.owl4fsrch.club/vnafvra97w/?q...,64.0,tkmowpikuk.owl4fsrch.club,25.0,0.0,club,14.338629,0.600000,0.000623,0.028541,4.0,1.0,0.0,0.0,0.0,33.0,0.516,16.0,0.250,2.0,1.0,NaN,5.0,0.125,0.0,2.0,72.0,0.0,0,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
167,https://acesseonline-fevereiro.net/luiza/?user...,98.0,acesseonline-fevereiro.net,26.0,0.0,net,13.534120,0.590909,0.038420,0.045336,3.0,0.0,0.0,0.0,0.0,74.0,0.755,6.0,0.061,3.0,1.0,0.0,NaN,0.102,1.0,2.0,106.0,0.0,0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0
212,https://visualize-detalhes-online.com/luiza/?u...,73.0,visualize-detalhes-online.com,29.0,0.0,com,26.192728,0.400000,0.522907,0.048629,3.0,0.0,0.0,0.0,0.0,53.0,0.726,2.0,0.027,2.0,1.0,0.0,7.0,0.137,1.0,90.0,394.0,NaN,NaN,0.0,98.333333,0.0,1.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,2.0,0.0,2.0,0.0,2.0,0.0

URL can contain `=` signs freely as it is part of the standard itself and nothing about it is malicious. This features would not be meaningful.

In [26]:
from sklearn.preprocessing import LabelEncoder
from joblib import Parallel, delayed

data["NoOfDigitsInDomain"] = data["Domain"].str.count(r"\d")
data["DigitRatioInDomain"] = data["NoOfDigitsInDomain"] / data["DomainLength"]
data["NoOfHyphensInDomain"] = data["Domain"].str.count("-")
data["HyphenRatioInDomain"] = data["NoOfHyphensInDomain"] / data["DomainLength"]
data["NoOfSpecialCharInDomain"] = data["Domain"].str.count(r"[^a-zA-Z0-9\.-]")
data["AlphabetRatioInDomain"] = (
    data["Domain"].str.count(r"[a-zA-Z]") / data["DomainLength"]
)
data["NoOfTokensInDomain"] = (
    data["Domain"]
    .fillna("")
    .str.split(r"[.-]")
    .apply(lambda x: len([t for t in x if t]))
)


# I am not sure about this feature, but we may try it as well
def shannon_entropy(s):
    if not isinstance(s, str) or len(s) == 0:
        return 0.0

    le = LabelEncoder()
    encoded = le.fit_transform(list(s))

    counts = np.bincount(encoded)
    probs = counts[counts > 0] / counts.sum()

    # Shannon entropy (base 2)
    return -np.sum(probs * np.log2(probs + 1e-12))


data["DomainEntropy"] = Parallel(n_jobs=-1, backend="loky")(
    delayed(shannon_entropy)(d) for d in data["Domain"].values
)

Fix the `TLD` feature.

In [27]:
import re
from urllib.parse import urlparse
from joblib import Parallel, delayed

ipv4_re = re.compile(r"^\d{1,3}(\.\d{1,3}){3}$")
ipv6_re = re.compile(r"^\[?[0-9a-fA-F:]+\]?$")


def extract_url_features(url):
    out = {
        "TLD": None,
        "TLDLength": 0,
        "IsDomainIP": 0,
        "IsHTTPS": 0,
        "NoOfSubDomain": 0,
    }

    if pd.isna(url):
        return out

    try:
        parsed = urlparse(url if "://" in url else "http://" + url)

        host = parsed.hostname
        if host is None:
            return out

        # HTTPS
        out["IsHTTPS"] = int(parsed.scheme.lower() == "https")

        # IP detection
        if ipv4_re.match(host) or ipv6_re.match(host):
            out["IsDomainIP"] = 1
            return out

        parts = host.lower().split(".")

        if len(parts) < 2:
            return out

        tld = parts[-1]

        # TLD sanity check
        if not tld.isalpha():
            return out

        out["TLD"] = tld
        out["TLDLength"] = len(tld)

        # subdomains = everything before (domain + tld)
        out["NoOfSubDomain"] = max(len(parts) - 2, 0)

        return out

    except Exception:
        return out


features = Parallel(n_jobs=-1, backend="loky")(
    delayed(extract_url_features)(u) for u in data["URL"].values
)
features = pd.DataFrame(features)

data[features.columns] = features

In [28]:
new_features = [
    "NoOfDigitsInDomain",
    "DigitRatioInDomain",
    "NoOfHyphensInDomain",
    "HyphenRatioInDomain",
    "NoOfSpecialCharInDomain",
    "AlphabetRatioInDomain",
    "NoOfTokensInDomain",
    "DomainEntropy",
]

data[new_features].describe().T

,count,mean,std,min,25%,50%,75%,max
NoOfDigitsInDomain,224040.0,0.881642,2.788403,0.0,0.000000,0.000000,0.000000,44.000000
DigitRatioInDomain,212764.0,0.031090,0.092012,0.0,0.000000,0.000000,0.000000,0.885714
NoOfHyphensInDomain,224040.0,0.281651,0.751233,0.0,0.000000,0.000000,0.000000,26.000000
HyphenRatioInDomain,212764.0,0.009931,0.023497,0.0,0.000000,0.000000,0.000000,0.419355
NoOfSpecialCharInDomain,224040.0,0.000174,0.015087,0.0,0.000000,0.000000,0.000000,2.000000
AlphabetRatioInDomain,212764.0,0.848039,0.101197,0.0,0.833333,0.875000,0.900000,0.978723
NoOfTokensInDomain,235795.0,3.270230,1.235126,0.0,3.000000,3.000000,4.000000,29.000000
DomainEntropy,235795.0,3.298751,0.850632,0.0,3.181366,3.456565,3.699471,4.975311

In [29]:
with pd.option_context("display.max_rows", None):
    display(pd.Series(data.columns))

0                            URL
1                      URLLength
2                         Domain
3                   DomainLength
4                     IsDomainIP
5                            TLD
6             URLSimilarityIndex
7           CharContinuationRate
8              TLDLegitimateProb
9                    URLCharProb
10                     TLDLength
11                 NoOfSubDomain
12                HasObfuscation
13            NoOfObfuscatedChar
14              ObfuscationRatio
15              NoOfLettersInURL
16              LetterRatioInURL
17               NoOfDegitsInURL
18               DegitRatioInURL
19               NoOfEqualsInURL
20                NoOfQMarkInURL
21            NoOfAmpersandInURL
22    NoOfOtherSpecialCharsInURL
23         SpacialCharRatioInURL
24                       IsHTTPS
25                    LineOfCode
26             LargestLineLength
27                      HasTitle
28                         Title
29         DomainTitleMatchScore
30            URLTitleMatchScore
31                    HasFavicon
32                        Robots
33                  IsResponsive
34               NoOfURLRedirect
35              NoOfSelfRedirect
36                HasDescription
37                     NoOfPopup
38                    NoOfiFrame
39         HasExternalFormSubmit
40                  HasSocialNet
41               HasSubmitButton
42               HasHiddenFields
43              HasPasswordField
44                          Bank
45                           Pay
46                        Crypto
47              HasCopyrightInfo
48                     NoOfImage
49                       NoOfCSS
50                        NoOfJS
51                   NoOfSelfRef
52                  NoOfEmptyRef
53               NoOfExternalRef
54                         label
55            NoOfDigitsInDomain
56            DigitRatioInDomain
57           NoOfHyphensInDomain
58           HyphenRatioInDomain
59       NoOfSpecialCharInDomain
60         AlphabetRatioInDomain
61            NoOfTokensInDomain
62                 DomainEntropy
dtype: object

In [30]:
features_to_remove = [
    # We remove the URL based features, because URLs in real life can be anything and may not really tell us anything about phishingness. The domain would be better.
    "URL",
    "URLLength",
    "URLSimilarityIndex",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfDegitsInURL",
    "DegitRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "SpacialCharRatioInURL",

    # We apply encoding ourselves.
    "TLDLegitimateProb",

    "Title",
]

data = data.drop(columns=features_to_remove)

In [31]:
with pd.option_context("display.max_rows", None):
    display(pd.Series(data.columns))

0                      Domain
1                DomainLength
2                  IsDomainIP
3                         TLD
4        CharContinuationRate
5                 URLCharProb
6                   TLDLength
7               NoOfSubDomain
8              HasObfuscation
9          NoOfObfuscatedChar
10           ObfuscationRatio
11                    IsHTTPS
12                 LineOfCode
13          LargestLineLength
14                   HasTitle
15      DomainTitleMatchScore
16         URLTitleMatchScore
17                 HasFavicon
18                     Robots
19               IsResponsive
20            NoOfURLRedirect
21           NoOfSelfRedirect
22             HasDescription
23                  NoOfPopup
24                 NoOfiFrame
25      HasExternalFormSubmit
26               HasSocialNet
27            HasSubmitButton
28            HasHiddenFields
29           HasPasswordField
30                       Bank
31                        Pay
32                     Crypto
33           HasCopyrightInfo
34                  NoOfImage
35                    NoOfCSS
36                     NoOfJS
37                NoOfSelfRef
38               NoOfEmptyRef
39            NoOfExternalRef
40                      label
41         NoOfDigitsInDomain
42         DigitRatioInDomain
43        NoOfHyphensInDomain
44        HyphenRatioInDomain
45    NoOfSpecialCharInDomain
46      AlphabetRatioInDomain
47         NoOfTokensInDomain
48              DomainEntropy
dtype: object

In [32]:
binary_columns = [col for col in data.columns if data[col].dropna().nunique() == 2]
binary_columns

['IsDomainIP',
 'HasObfuscation',
 'IsHTTPS',
 'HasTitle',
 'HasFavicon',
 'Robots',
 'IsResponsive',
 'NoOfURLRedirect',
 'NoOfSelfRedirect',
 'HasDescription',
 'HasExternalFormSubmit',
 'HasSocialNet',
 'HasSubmitButton',
 'HasHiddenFields',
 'HasPasswordField',
 'Bank',
 'Pay',
 'Crypto',
 'HasCopyrightInfo',
 'label']

In [33]:
data = data.rename(
    columns={
        "NoOfURLRedirect": "HasURLRedirect",
        "NoOfSelfRedirect": "HasSelfRedirect",
    }
)
binary_columns = [col for col in data.columns if data[col].dropna().nunique() == 2]

In [34]:
data[binary_columns] = data[binary_columns].astype("Int8")

In [35]:
discrete_columns = [col for col in data.columns if col.startswith("NoOf") | ("Length" in col)]
discrete_columns.append("LineOfCode")
np.setdiff1d(data.columns, np.union1d(discrete_columns, binary_columns))

array(['AlphabetRatioInDomain', 'CharContinuationRate',
       'DigitRatioInDomain', 'Domain', 'DomainEntropy',
       'DomainTitleMatchScore', 'HyphenRatioInDomain', 'ObfuscationRatio',
       'TLD', 'URLCharProb', 'URLTitleMatchScore'], dtype=object)

In [36]:
data[discrete_columns] = data[discrete_columns].astype("Int64")

In [37]:
object_columns = [col for col in data.columns if data.dtypes[col] == "object"]
object_columns

['Domain', 'TLD']

In [38]:
from functools import reduce
float_columns = np.setdiff1d(data.columns, reduce(np.union1d, (binary_columns, discrete_columns, object_columns)))
float_columns

array(['AlphabetRatioInDomain', 'CharContinuationRate',
       'DigitRatioInDomain', 'DomainEntropy', 'DomainTitleMatchScore',
       'HyphenRatioInDomain', 'ObfuscationRatio', 'URLCharProb',
       'URLTitleMatchScore'], dtype=object)

In [39]:
data = data.rename(columns={col: "B" + col for col in binary_columns})
data = data.rename(columns={col: "D" + col for col in discrete_columns})
data = data.rename(columns={col: "O" + col for col in object_columns})
data = data.rename(columns={col: "F" + col for col in float_columns})

data = data.rename(columns={"Blabel": "label"})

In [40]:
data.to_csv("feature-engineering.csv", index=False)